/**
 * The CV PDFs live in `public/` and are regenerated by `npm run cv:build`
 * from `cv/content.<locale>.json`. Shared by the header button and the hero
 * variants so the three filenames exist in exactly one place.
 */
export const getCVUrl = (locale: string) => {
  switch (locale) {
    case "sk":
      return "/Varju-CV-SK.pdf";
    case "hu":
      return "/Varju-CV-HU.pdf";
    default:
      return "/Varju-CV-EN.pdf";
  }
};

/** Matches the existing umami event names so historical data stays comparable. */
export const cvUmamiEvent = (locale: string) =>
  `CV downloaded in ${locale} language`;
