/**
 * The CV PDFs live in `public/` and are regenerated by `npm run cv:build`
 * from `cv/content.<locale>.json`. Shared by the nav's CV button, the
 * terminal's `cv` command and the ⌘K palette, so the three filenames exist in
 * exactly one place.
 */
export const getCVUrl = (locale: string) => {
  switch (locale) {
    case "sk":
      return "/Varju-CV-SK.pdf";
    case "hu":
      return "/Varju-CV-HU.pdf";
    default:
      return "/Varju-CV-EN.pdf";
  }
};

/** Matches the existing umami event names so historical data stays comparable. */
export const cvUmamiEvent = (locale: string) =>
  `CV downloaded in ${locale} language`;

declare global {
  interface Window {
    umami?: { track?: (event: string) => void };
  }
}

/**
 * Programmatic equivalent of the `data-umami-event` attribute used on the
 * header button. Needed where the download isn't triggered by a click on an
 * element we control — e.g. the terminal's `cv` command. Safe to call
 * when the analytics script hasn't loaded (or is blocked).
 */
export const trackCvDownload = (locale: string) => {
  try {
    window.umami?.track?.(cvUmamiEvent(locale));
  } catch {
    /* analytics blocked — never let this break a download */
  }
};
